name: CI/CD Pipeline

# Controls when the workflow will run
on:  
  push:
    branches:
      -main   
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:    
      - name: CHeckout repository
        uses: actions/checkout@v2
    
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1         
    
      - name: Install dependencies
        env:
          CI: true
        run: npm ci
#함수 코드 빌드
      - name: Build
        run : npm run build
      - name: Create zip package
        run : zup j deploy.zip ./dist/*
      - name: Deploy to Lambda
        run: aws lambda update-function-code --function-name NBA-function --zip-file fileb://deploy.zip
      
